ONSdigital/dp-search-reindex-api

swagger.yaml
The GET /health endpoint has been added to the swagger.
The health endpoint returns 200 status OK response with no checks on dependent services.
Check that the details in the swagger spec look correct. 
Use the Swagger Editor to check that there are no errors: https://editor.swagger.io/
Anyone but me
=> Add details of health endpoint to the swagger

ci/audit.yml, ci/lint.yml
Just an update to the audit docker image version to be consistent with the other layers
n/a
Anyone except me
=> Update audit docker image version to be consistent

main_test.go
Discards logging while running component tests so it's possible to see a clean output
Run tests, ensure appropriate output is seen
Ella
=> quieten logging while running component tests

swagger.yaml
- Organise swagger to be more readable
- Add patch endpoint in swagger
**N.B The endpoint is currently not available in dp-search-reindex-api. I am currently implementing it**
- Check if the changes make sense
- Anyone
=> add patch endpoint in swagger spec

sdk/client.go, sdk/mocks/client.go, sdk/v1/client.go, sdk/v1/client_test.go
See title, tests updated too
Check client instantiation makes sense, check for typos
Anyone
=> Update client instantiation with methods New and NewClientWithHealth

.golangci.yml, sdk/v1/client.go
See title
Check new error message makes sense
Anyone
=> Define which client is set to nil in client error message

.golangci.yml, sdk/client.go, sdk/mocks/client.go, sdk/v1/client.go, sdk/v1/client_test.go
Change how we instantiate the client and check for nil client values
- Sanity check changes
Anyone
=> Update sdk client for search reindex api

models/job_test.go, mongo/tasks.go, sdk/client.go, sdk/mocks/client.go, sdk/v1/client.go, sdk/v1/client_test.go
* client for endpoint /jobs/{id}/tasks
* fix failing junit for timestamp error
* fix for lint CI error due to golang version
* CI pass
* anyone
=> client implementation for task counts

sdk/v1/client.go, sdk/v1/client_test.go
* Response header updates for job/{id}/tasks endpoint
* Add eTag functionality
* Code sense check
* CI pass
* anyone
=> response header updates for endpoint job/{id}/tasks 

models/metadata.go, models/task.go, sdk/client.go, sdk/client_test.go, sdk/mocks/client.go, sdk/v1/client.go, sdk/v1/client_test.go, swagger.yaml
* Client for endpoint /jobs/{id}/tasks/{taskname}
* response header updates for eTag functionality
* swagger doc updates
* CI pass
* Anyone
=> Client for getting a specific task with header updates

models/task.go, sdk/client.go, sdk/mocks/client.go, sdk/v1/client.go, sdk/v1/client_test.go
* Task model changes using pass by reference  instead of pass by value
* CI pass
* Anyone
=> Task model updates for client with pass by reference

sdk/client.go, sdk/client_test.go, sdk/v1/client_test.go
* etag feature updates for GET endpoint job/{jobid}/task/{taskname}
* CI pass
* anyone
=> etag feature updates for job-task-taskname

api/interfaces.go, api/mock/data_storer.go, api/mock/reindex_requested_producer.go, api/tasks.go, features/steps/datastore_steps.go, features/steps/task_steps.go, mongo/tasks.go, service/mock/healthCheck.go, service/mock/initialiser.go, service/mock/kafka_producer.go, service/mock/mongo_data_storer.go, service/mock/server.go
* function update using new struct to replace offsets and mongo data limit as parameters
* component/unit tests updates
* CI pass
* anyone
=> new struct updates for mongo query

sdk/client.go, sdk/mocks/client.go, sdk/v1/client.go, sdk/v1/client_test.go
* Client for getTasks to get number to tasks assigned to a job
* CI pass
* Anyone
=> Extend client to get tasks

sdk/client.go, sdk/mocks/client.go, sdk/v1/client.go, sdk/v1/client_test.go
* Client for getJob to get a job with JobId
* CI pass
* Anyone
=> Extend client to get a Job

api/interfaces.go, api/jobs.go, api/jobs_test.go, api/mock/data_storer.go, features/latest_version_features/getting_jobs.feature, mongo/jobs.go, sdk/client.go, sdk/mocks/client.go, sdk/v1/client.go, sdk/v1/client_test.go, service/mock/mongo_data_storer.go
* Client for getJobs to get list of jobs
* Include query parameters, offset, limit and others by using the Options struct in method signature
* unit test
* CI pass
* Anyone
=> Extend client to get jobs endpoint

api/api.go, api/helper.go, api/helper_test.go, api/interfaces.go, api/jobs.go, api/jobs_test.go, api/mock/data_storer.go, apierrors/errors.go, event/producer.go, event/producer_test.go, features/latest_version_features/patch_job_state_fail.feature, features/latest_version_features/patch_job_state_success.feature, features/latest_version_features/posting_a_job.feature, features/latest_version_features/posting_a_task.feature, features/latest_version_features/putting_number_of_tasks.feature, features/steps/job_steps.go, features/steps/steps.go, features/steps/task_steps.go, features/v1_features/latest_version_features/patch_job_state_fail.feature, features/v1_features/latest_version_features/patch_job_state_success.feature, features/v1_features/latest_version_features/posting_a_job.feature, features/v1_features/latest_version_features/posting_a_task.feature, features/v1_features/latest_version_features/putting_number_of_tasks.feature, models/job.go, models/job_test.go, mongo/data_store.go, mongo/jobs.go, mongo/tasks.go, reindex/reindex.go, service/mock/mongo_data_storer.go
- Refactor the `CreateJob` handler to be simplified and separate the data layer from the handler function
- Update the unit and component tests accordingly
- Check if all the tests pass
- Check if the code changes make sense
**Describe who worked on the changes, so that other people can review**
- Anyone
=> refactor `CreateJob` handler

api/interfaces.go, api/jobs.go, api/jobs_test.go, api/mock/data_storer.go, apierrors/errors.go, features/latest_version_features/getting_a_job.feature, features/steps/api_feature.go, features/steps/helper.go, features/steps/job_steps.go, features/v1_features/latest_version_features/getting_a_job.feature, mongo/jobs.go, service/mock/mongo_data_storer.go
- Component test added for empty job id given when getting a job
- Return pointer to models.Job and return nil when there is an error (for `GetJob` and `FindJob`)
- Check if the changes make sense
- Check if all the test passes
- Anyone
=> refactor `GetJobHandler` data layer

api/interfaces.go, api/jobs.go, api/jobs_test.go, api/mock/data_storer.go, mongo/jobs.go, service/mock/mongo_data_storer.go
- Separate getting jobs count functionality in separate function `getJobsCount`
- Return pointer to `models.Jobs`
- Check if the code changes make sense
- Check if all the test passes
- Anyone
=> refactor `GetJobsHandler` data layer

api/interfaces.go, api/jobs_test.go, api/mock/data_storer.go, api/tasks.go, api/tasks_test.go, features/steps/datastore_steps.go, features/steps/task_steps.go, mongo/tasks.go, service/interfaces.go, service/mock/mongo_data_storer.go
- Added unit tests for `GetTaskHandler` and `GetTasksHandler`
- Return pointer to `models.Task` and `models.Tasks`
- Whenever error is received, return `nil` for task
- Check if the changes make sense
- Check if the test passes
- Anyone
=> refactor `GetTaskHandler` and `GetTasksHandler` data layer

api/jobs.go, api/jobs_test.go, features/latest_version_features/posting_a_job.feature, features/v1_features/latest_version_features/posting_a_job.feature, models/job.go, models/job_test.go
Describe what you have changed and why
- set eTag on ETag response header in `CreateJobHandler`
- Update unit and component tests
Describe the steps required to test the changes.
- Check if the tests pass
- Check if the code changes make sense
Describe who worked on the changes, so that other people can review.
- Anyone
=> set eTag on ETag response header in `CreateJobHandler`

api/tasks.go, api/tasks_test.go, features/latest_version_features/posting_a_task.feature, features/v1_features/latest_version_features/posting_a_task.feature
- Update tests to involve etag
- Add AcquireLock and Unlock when accessing job resource from mongo
- Tidy some unit test
- Check if the tests passes
- Check if the code changes make sense
- Anyone
=> update tests and add mongo lock for POST `/jobs/{id}/tasks`

sdk/client.go, sdk/mocks/client.go, sdk/v1/client.go, sdk/v1/client_test.go
Add client sdk for number of docs api.
Please check if the changes make sense.
Anyone except me.
=> Add client sdk for number of docs api
